### PR TITLE
Rename analysis_options to analysis_options.yaml

### PR DESCRIPTION
**Pull request by robbecker-wf**
# Overview
This PR changes the name of the Dart analysis options file to the correct one that will be supported going forward.
`.analysis_options` is deprecated
`analysis_options.yaml` is the correct one.

# Tests
No tests should need to be updated or performed. CI passing is sufficient.

### CODE REVIEW

**Comment by aviary3-wk** [comment]
## Security Insights
No security relevant content was detected by automated scans.

## Action Items
* Review PR for [security impact](https://wiki.atl.workiva.net/display/SECURITY/Development+Security+Review+Guidelines); comment "security review required" if needed or unsure
* Verify [`aviary.yaml`](https://dev.workiva.net/docs/information-security/aviary#configuring-aviary) coverage of security relevant code
---
_Questions or Comments? Reach out on HipChat: InfoSec Forum._

**Comment by robbecker-wf** [comment]
Quality Review / QA: +1

- [x] Dev +1

Merging into master.
@Workiva/release-management-p for merge into master

**Comment by robbecker-wf** [comment]
@jayudey-wf can u merge?

**Comment by jayudey-wf** [comment]
doesn't look like i have merge access
screen shot 2018-06-26 at 12 54 56 pm

**Comment by tayloranderson-wf** [comment]
+1

**Pull request merged**
