### PR TITLE
Update dependency_validator

### PR DESCRIPTION
**Pull request by robbecker-wf**
Updating dependency_validator allows the latest version of analyzer to resolve

### CODE REVIEW

**Comment by aviary3-wk** [comment]
## Security Insights
No security relevant content was detected by automated scans.

## Action Items
* Review PR for [security impact](https://wiki.atl.workiva.net/display/SECURITY/Development+Security+Review+Guidelines); comment "security review required" if needed or unsure
* Verify [`aviary.yaml`](https://wiki.atl.workiva.net/pages/viewpage.action?pageId=42762752#SecurityInsightFramework&Tooling-ConfiguringAviary) coverage of security relevant code
---
_Questions or Comments? Reach out on Slack: #support-infosec._

**Comment by robbecker-wf** [comment]
With this update we can get to the latest analyzer (5.5.0 at time of writing)

**Comment by robbecker-wf** [comment]
QA+1 CI Passes

**Review by matthewnitschke-wk — APPROVED** [review]

**Comment by robbecker-wf** [comment]
@Workiva/release-management-p

**Review by rmconsole-wf — APPROVED** [review]
+1 from RM

**Pull request merged**
