### PR TITLE
Add changelog for 2.1.6

### PR DESCRIPTION
**Pull request by travissanderson-wf**
Updates the changelog so we can tag 2.1.6

### CODE REVIEW

**Comment by aviary3-wk** [comment]
## Security Insights
No security relevant content was detected by automated scans.

## Action Items
* Review PR for [security impact](https://wiki.atl.workiva.net/display/SECURITY/Development+Security+Review+Guidelines); comment "security review required" if needed or unsure
* Verify [`aviary.yaml`](https://wiki.atl.workiva.net/pages/viewpage.action?pageId=42762752#SecurityInsightFramework&Tooling-ConfiguringAviary) coverage of security relevant code
---
_Questions or Comments? Reach out on Slack: #support-infosec._

**Review by kerbyseeley-wf — DISMISSED** [review]

**Review by brettmeyer-wk — DISMISSED** [review]
+10

**Comment by travissanderson-wf** [comment]
Sorry, my coffee is still kicking in, I think we want to evaluate the deprecation PR and merge it before we cut this release

**Review by danielway-wk — APPROVED** [review]
+10

**Review by jihongkim-wk — APPROVED** [review]

**Comment by travissanderson-wf** [comment]
@Workiva/release-management-p

**Review by rmconsole-wf — APPROVED** [review]
+1 from RM

**Pull request merged**
