### PR TITLE
Performance Improvement for Load and Search

### PR DESCRIPTION
**Pull request by Ronbb**
While experimenting with the RTree, I compared my node searcher implementations using List and Queue. I noticed suboptimal performance of RTree's Load. Therefore, I made the following attempts:

```text
Before(master):

Name                                    Result (microseconds)
--------------------------------------------------------------
Insert 100                                 8643.25
Insert 1000                              209028.80
Insert 10000                            4812995.00
Load 100                                   1065.91
Load 1000                                 28855.66
Load 10000                               409432.20
Remove 5k                                479201.20
Search/Iterate (using Insert) 100         19185.07
Search/Iterate (using Insert) 1000        86072.71
Search/Iterate (using Insert) 10000      287112.00
Search/Iterate (using Load) 100           26881.30
Search/Iterate (using Load) 1000          92531.55
Search/Iterate (using Load) 10000        251928.44

Transform the comparison functions into inline closures:

Name                                    Result (microseconds)
--------------------------------------------------------------
Insert 100                                 8420.19 (97.42%)
Insert 1000                              202726.40 (96.98%)
Insert 10000                            4762420.00 (98.95%)
Load 100                                    773.25 (72.54%)
Load 1000                                 17572.26 (60.90%)
Load 10000                               220203.30 (53.78%)
Remove 5k                                464622.40 (96.96%)
Search/Iterate (using Insert) 100         19809.47 (103.25%)
Search/Iterate (using Insert) 1000        86743.25 (100.78%)
Search/Iterate (using Insert) 10000      265700.75 (92.54%)
Search/Iterate (using Load) 100           26341.89 (97.99%)
Search/Iterate (using Load) 1000          94510.14 (102.14%)
Search/Iterate (using Load) 10000        253090.75 (100.46%)

Refactor RTreeContributor (include above changes)

Name                                    Result (microseconds)
--------------------------------------------------------------
Insert 100                                 8386.57 (97.03%)
Insert 1000                              201995.90 (96.64%)
Insert 10000                            4705896.00 (97.77%)
Load 100                                    767.79 (72.03%)
Load 1000                                 16469.92 (57.08%)
Load 10000                               215497.30 (52.63%)
Remove 5k                                214634.60 (44.79%)
Search/Iterate (using Insert) 100          9971.14 (51.97%)
Search/Iterate (using Insert) 1000        38198.02 (44.38%)
Search/Iterate (using Insert) 10000      124946.12 (43.52%)
Search/Iterate (using Load) 100           14543.00 (54.10%)
Search/Iterate (using Load) 1000          49877.24 (53.90%)
Search/Iterate (using Load) 10000        127431.63 (50.58%)
```

### CODE REVIEW

**Comment by aviary-wf** [comment]
## Security Insights
No security relevant content was detected by automated scans.

## Action Items
* Review PR for [security impact](https://wiki.atl.workiva.net/display/SECURITY/Development+Security+Review+Guidelines); comment "security review required" if needed or unsure
* Verify [`aviary.yaml`](https://wiki.atl.workiva.net/pages/viewpage.action?pageId=42762752#SecurityInsightFramework&Tooling-ConfiguringAviary) coverage of security relevant code
---
_Questions or Comments? Reach out on Slack: #support-infosec._

**Comment by travissanderson-wf** [comment]
Hi @Ronbb, thanks for the PR! These results look very promising and we will be reviewing this soon. Do you think you could add some details (for our knowledge) on what methodology you used to discover these inefficiencies and how you came to the solutions you've got in your commits? We'd appreciate it, but we'll get these changes adopted either way if you're not interested in sharing. Thanks again!

**Comment by Ronbb** [comment]
Hi @travissanderson-wf, Please bear in mind that my English proficiency may not be very high, so my expressions might not be as accurate as I would like them to be. Your understanding and assistance are greatly appreciated.

I am not very familiar with DartVM, but based on some of my C++ development experience, the reasons for the performance issue may be as follows:

1. A frequent large number of function calls, particularly those involving extensive numerical comparisons, lead to a performance drop. To address this, I have marked some functions as inline, and you can find decorators like @pragma('vm:prefer-inline') in the code.

2. (This is a speculation) When using `extends`, it may generate something similar to C++ virtual tables and may implicitly call `super()` during construction. Therefore, I changed the way I depend on `RTreeContributor` from 'extends' to 'implements.'

By the way, I conducted performance testing on Windows, not the web platform (I noticed you mentioned 'getReifiedType,' which is specifically used on the web platform). Therefore, our test results may vary.

**Comment by travissanderson-wf** [comment]
Thanks @Ronbb! I measured in the VM and in web and saw similar performance improvements, but they're probably for different reasons. One of the biggest gains in the web was the reduction in getReifiedType which we think may be because the Node classes are using covariant types on `children`, which seems to give Dart on the web a hard time. Switching to the extension on Rectangle avoided that cost when doing `overlap` and I'm thinking if we could eliminate covariants we'd see similar improvements elsewhere in the code.

Regarding your first point, I saw similar gains in the web for search because of the inlining. Good catch!

Your English is great. Thanks again for your PR, we'll try to get it in here soon.

**Pull request merged**
