### PR TITLE
RM-222909 Release r_tree 2.1.6

### PR DESCRIPTION
**Pull request by rmconsole-readonly-wk**
Pull Requests included in release:
* Patch changes:
	* [Fix load state errors](https://github.com/Workiva/r_tree/pull/71)
	* [Add changelog for 2.1.6](https://github.com/Workiva/r_tree/pull/72)
	* [Deprecate symbols not intended to be public for upcoming 3.0 release](https://github.com/Workiva/r_tree/pull/73)

Requested by: @travissanderson-wf

Diff Between Last Tag and Proposed Release: https://github.com/Workiva/r_tree/compare/2.1.5...Workiva:release_r_tree_2.1.6
Diff Between Last Tag and New Tag: https://github.com/Workiva/r_tree/compare/2.1.5...2.1.6

The logs for the request that created this PR can be found [here](https://w-rmconsole.appspot.com/release/release_event/6122762573840384/logs/)
This pull request can be recreated by clicking [here](https://w-rmconsole.appspot.com/api/v2/rosie/reTriggerReleaseEvents/6122762573840384/?repo_name=Workiva%2Fr_tree&pull_number=74)

### CODE REVIEW

**Review by travissanderson-wf — APPROVED** [review]
+10

**Comment by aviary3-wk** [comment]
## Security Insights
No security relevant content was detected by automated scans.

## Action Items
* Review PR for [security impact](https://wiki.atl.workiva.net/display/SECURITY/Development+Security+Review+Guidelines); comment "security review required" if needed or unsure
* Verify [`aviary.yaml`](https://wiki.atl.workiva.net/pages/viewpage.action?pageId=42762752#SecurityInsightFramework&Tooling-ConfiguringAviary) coverage of security relevant code
---
_Questions or Comments? Reach out on Slack: #support-infosec._

**Review by jihongkim-wk — APPROVED** [review]

**Comment by travissanderson-wf** [comment]
@Workiva/release-management-p

**Review by rmconsole-wf — APPROVED** [review]
+1 from RM

**Pull request merged**
